heat_template_version: "2013-05-23"

description: Main hot for creating vnf

parameters:
  image_name:
    type: string
    default: centos_7_2

  flavor_name:
    type: string
    default: m1.medium


resources:
  workflow:
    type: OS::Mistral::Workflow
    properties:
      type: direct
      tasks:
        - name: create_stack
          action: heat.stacks_create stack_name="vnfd" template=<% $.stack_template %>
          retry:
             delay: 5
             count: 10
          on_success:
            - wait_stack_complete
        - name: wait_stack_complete
          action: heat.stacks_get stack_id=<% $.stack_name %>
          wait_before: 5
          on_success:
           - wait_stack_complete: <% $.wait_stack_complete.stack_status=CREATE_IN_PROGRESS %>
           - get_vm_id: <% $.wait_stack_complete.stack_status=CREATE_COMPLETE %>
      input:
        stack_template: {get_file: "./hot/vnf.yaml"}




