heat_template_version: "2014-10-16"

description: Main hot for creating vnf

parameters:
  image_name:
    type: string
    default: centos_7_2

  flavor_name:
    type: string
    default: m1.medium

  net_name:
    type: string

  # public_net:
    # type: string

  sshkey_name:
    type: string

  # sshkey_private:
    # type: string
    
resources:
  node_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net_name }

  # node_floating_ip:
  #   type: OS::Neutron::FloatingIP
  #   properties:
  #     floating_network: { get_param: public_net }
  #     port_id: { get_resource: node_port }

  # node_floating_ip_ac:
  #   type: OS::Neutron::FloatingIPAssociation
  #   properties:
  #     floatingip_id: 3c2746c9-c983-4ebc-85d9-01e06e036609
  #     port_id: { get_resource: node_port }

  oam:
    type: OS::Nova::Server  
    properties:  
      image: {get_param: image_name}
      key_name: {get_param: sshkey_name}
      name: OAM
      flavor: {get_param: flavor_name}
      networks:
        - port: { get_resource: node_port }
      user_data_format: RAW
      user_data: |
        #cloud-config
        disable_root: False
        password: root123
        chpasswd:
            list: |
                root:root123
            expire: False
        ssh_pwauth: True


outputs:
  # instance_ip:
    # description: The URL of the website
    # value: {get_param: sshkey_private}

