heat_template_version: 2013-05-23  

description: >
  This is how you can provide a longer description
  of your template that goes over several lines.

parameters:
  cbam:
    type: json
    default: {}

  image_name:
    type: string
    default: rhel-7.2

  flavor_name:
    type: string
    default: m1.medium

  net_name:
    type: string
    default: CBAM

resources:
  vnf_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: saamlite
      # public_key: { get_param: [ cbam, publicSshKey ] }

  oam:  
    type: oam.yaml 
    properties:  
      image_name: {get_param: image_name}
      sshkey_name: {get_resource: vnf_keypair}
      flavor_name: {get_param: flavor_name}
      net_name: { get_param: net_name }
      # sshkey_private: {get_attr: [vnf_keypair, private_key]}
      # public_net: { get_param: public_net }

  be_aspect_group:  
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: be.yaml
        properties:  
          image_name: {get_param: image_name}
          sshkey_name: {get_resource: vnf_keypair}
          flavor_name: {get_param: flavor_name}
          net_name: { get_param: net_name }
          # public_net: { get_param: public_net }
          index: '%index%'

outputs:
  private_key:
    description: The private_key
    # value: {get_param: [ cbam, privateSshKey ]}
