---


- name: check jdk variable 
  shell: cat /etc/profile
  register: result

- name: jdk variable configuration /etc/profile file
  shell: /bin/echo {{ item }} >> /etc/profile; source /etc/profile
  when: result.stdout.find('JAVA_HOME') == -1
  with_items:
     - export JAVA_HOME=/usr/java/jdk1.7.0_45
     - export JAVA_BIN=/usr/java/jdk1.7.0_45/bin
     - export PATH=$PATH:$JAVA_HOME/bin
     - export JRE_HOME=${JAVA_HOME}/jre
     - export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
     - export JAVA_HOME JAVA_BIN PATH JRE_HOME CLASSPATH

- name: check jdk variable 
  shell: cat /root/.bashrc
  register: bashrc_result

- name: jdk variable configuration /root/.bashrc file
  shell: /bin/echo {{ item }} >> /root/.bashrc
  when: bashrc_result.stdout.find('JAVA_HOME') == -1
  with_items:
     - export JAVA_HOME=/usr/java/jdk1.7.0_45
