heat_template_version: "2014-10-16"

description: Main hot for creating vnf

parameters:
  image_name:
    type: string
    default: centos_7_2

  flavor_name:
    type: string
    default: m1.medium

  net_name:
    type: string
    default: net1

  public_net:
    type: string
    default: external

  num_be:
    type: number
    default: 2

  num_fe:
    type: number
    default: 2

resources:
  vnf_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: vnfkey
      public_key: 
        get_file: http://10.16.9.119/noCAMB/keypair/vnf_key.pub
 
  vnf_oam:  
    type: oam.yaml 
    properties:  
      image_name: {get_param: image_name}
      sshkey_name: {get_resource: vnf_keypair}
      flavor_name: {get_param: flavor_name}
      net_name: { get_param: net_name }
      public_net: { get_param: public_net }

  vnf_be:  
    type: be.yaml 
    properties:  
      image_name: {get_param: image_name}
      sshkey_name: {get_resource: vnf_keypair}
      flavor_name: {get_param: flavor_name}
      net_name: { get_param: net_name }
      num_vm: { get_param: num_be }

  vnf_fe:  
    type: fes.yaml 
    properties:  
      image_name: {get_param: image_name}
      sshkey_name: {get_resource: vnf_keypair}
      flavor_name: {get_param: flavor_name}
      net_name: { get_param: net_name }
      num_vm: { get_param: num_fe }

outputs:
  oam_floating_ip:
    description: The IP of the OAM
    value: {get_attr: [vnf_oam, resource.node_floating_ip, floating_ip_address]}

  fe_ips:
    description: The IP of the FEs
    value: {get_attr: [vnf_fe, instances_ip]}