---

#- name: create pip directory on oam servers
#  file: path=/home/ansible/main/roles/oam/files/pip state=directory

#- name: copy pip files to oam servers
#  copy: src=../files/pip dest=/home/ansible/

#- name: copy base rpm packages to oam servers
#  copy: src=../files/packages dest=/home/ansible/
#
#- name: install gcc on oam
#  shell: rpm -ivh /home/ansible/main/roles/oam/files/packages/{{ item }}
#  with_items:
#    - libquadmath-4.8.5-4.el7.x86_64.rpm
#    - mpfr-3.1.1-4.el7.x86_64.rpm
#    - libmpc-1.0.1-3.el7.x86_64.rpm
#    - kernel-headers-3.10.0-327.el7.x86_64.rpm
#    - glibc-headers-2.17-105.el7.x86_64.rpm
#    - glibc-devel-2.17-105.el7.x86_64.rpm
#    - cpp-4.8.5-4.el7.x86_64.rpm
#    - gcc-4.8.5-4.el7.x86_64.rpm
#    - libstdc++-devel-4.8.5-4.el7.x86_64.rpm
#    - gcc-c++-4.8.5-4.el7.x86_64.rpm
#    - libgfortran-4.8.5-4.el7.x86_64.rpm
#    - libquadmath-devel-4.8.5-4.el7.x86_64.rpm
#    - gcc-gfortran-4.8.5-4.el7.x86_64.rpm
#    - python-devel-2.7.5-34.el7.x86_64.rpm
#    - zlib-devel-1.2.7-15.el7.x86_64.rpm
#    - libverto-devel-0.2.5-4.el7.x86_64.rpm
#    - libsepol-devel-2.1.9-3.el7.x86_64.rpm
#    - keyutils-libs-devel-1.5.8-3.el7.x86_64.rpm
#    - libcom_err-devel-1.42.9-7.el7.x86_64.rpm
#    - pcre-devel-8.32-15.el7.x86_64.rpm
#    - libselinux-devel-2.2.2-6.el7.x86_64.rpm
#    - krb5-devel-1.13.2-10.el7.x86_64.rpm
#    - openssl-devel-1.0.1e-42.el7.9.x86_64.rpm
#    - libffi-devel-3.0.13-16.el7.x86_64.rpm

- name: install gcc openssl-devel for ansible
  yum: name={{ item }} state=present  disablerepo=* enablerepo=packages
  with_items:
    - python-devel
    - openssl-devel
    - zlib-devel
    - gcc
    - openssl-devel
    - libffi-devel

- name: install pip
  command: python /home/ansible/main/roles/oam/files/pip/get-pip.py --no-wheel --no-setuptools --no-index --find-links=/home/ansible/main/roles/oam/files/pip/

- name: install the packages that ansible depend on
  command: pip install paramiko PyYAML Jinja2 httplib2 six --no-index --find-links=/home/ansible/main/roles/oam/files/pip/

- name: install ansible base package
  command: pip install ansible --no-index --find-links=/home/ansible/main/roles/oam/files/pip/

- name: cteate /etc/ansible directory
  file: path=/etc/ansible state=directory

- name: copy ansible.cfg file to /etc/ansible
  template: src=../templates/ansible.cfg dest=/etc/ansible/

